server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://127.0.0.1:5173"
              - "http://127.0.0.1:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/productos/**
        - id: ordenes-service
          uri: lb://ORDENES-SERVICE
          predicates:
            - Path=/ordenes/**
        - id: pagos-service
          uri: lb://PAGOS-SERVICE
          predicates:
            - Path=/pagos/**
        - id: broker-message-be
          uri: lb://BROKER-MESSAGE-BE
          predicates:
            - Path=/api/mail/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka/